Sampling and Random Variable

In [1]:
import pandas as pd
import numpy as np

In [2]:
np.random.seed(42)
data = {
    "student_id":range(1,1001),
    "marks":np.random.normal(70,10,1000),
    "study_hours":np.random.normal(5,2,1000)
}
df = pd.DataFrame(data)
df

     student_id      marks  study_hours
0             1  74.967142     7.798711
1             2  68.617357     6.849267
2             3  76.476885     5.119261
3             4  85.230299     3.706126
4             5  67.658466     6.396447
..          ...        ...          ...
995         996  67.188997     7.140300
996         997  87.976865     4.946957
997         998  76.408429     3.236251
998         999  64.288210     4.673866
999        1000  75.725828     3.510195

[1000 rows x 3 columns]

In [3]:
print("Understanding the population dataset")
print(f"Population mean of marks: {df["marks"].mean()}")
print(f"Population std of marks: {df["marks"].std()}")
print(f"Correlation between marks and study_hours {df["marks"].corr(df["study_hours"])}")

Understanding the population dataset
Population mean of marks: 70.19332055822326
Population std of marks: 9.792159381796756
Correlation between marks and study_hours -0.04039987129344418

Taking a random sample

In [4]:
sample=df.sample(n=50)
sample

     student_id      marks  study_hours
749         750  55.933389     7.002092
771         772  64.375332     8.390102
71           72  85.380366     5.954082
899         900  61.830643     4.409039
242         243  75.049873     3.836638
236         237  49.748574     8.355402
829         830  67.182154     5.037699
304         305  69.790984     6.073020
459         460  58.021221     6.346363
811         812  65.602689     5.293586
171         172  61.841897     5.562383
626         627  60.103952     4.105356
502         503  56.014324     3.363602
617         618  77.257666     3.496418
662         663  69.672467     0.756290
981         982  74.254576     2.240764
375         376  62.326524     4.581353
621         622  74.714684     2.123444
726         727  70.184339     3.928073
233         234  63.483997    10.159419
297         298  73.072995     4.419451
249         250  74.049817     1.888209
243         244  78.657552     2.970487
691         692  81.593298     4.050193
602         603  78.696059     3.708072
116         117  69.652882     9.806831
141         142  83.071428     7.751414
830         831  56.555495     6.416429
757         758  71.848361     6.905749
665         666  71.064302     4.954264
409         410  75.144388     4.498334
879         880  81.883933     3.388260
134         135  60.805758     4.511687
752         753  60.241267     3.691849
318         319  73.241664     3.780976
536         537  61.395866     6.027200
202         203  80.830512     5.244595
345         346  72.320499     2.030204
768         769  63.730329     5.246410
219         220  70.818741     9.290298
760         761  64.243622     8.279929
612         613  72.799686     6.766220
687         688  66.251792     5.402319
457         458  59.647577     5.762317
296         297  78.995999     6.838153
63           64  58.037934     1.520572
508         509  70.485216     5.176814
344         345  65.289617     6.899108
505         506  65.128746     4.093544
340         341  61.777796     5.321148

Sample statistics calculation

In [5]:
print("Understanding sample")
print(f"Sample mean of marks = {sample["marks"].mean()}")
print(f"Sample std of marks = {sample["marks"].std()}")

Understanding sample
Sample mean of marks = 68.48205569720066
Sample std of marks = 8.256526294709559

Comparing sample statistics and population parameters - they are not exactly same, but they are nearly equal as the sample size is large enough and also the sampling is done randomly.

Multiple Samples

In [6]:
#5 samples of size 50
sample1=df.sample(n=50)
sample2=df.sample(n=50)
sample3=df.sample(n=50)
sample4=df.sample(n=50)
sample5=df.sample(n=50)
# mean of each samples
print(f"Mean of sample 1 is {sample1["marks"].mean()}")
print(f"Mean of sample 2 is {sample2["marks"].mean()}")
print(f"Mean of sample 3 is {sample3["marks"].mean()}")
print(f"Mean of sample 4 is {sample4["marks"].mean()}")
print(f"Mean of sample 5 is {sample5["marks"].mean()}")

Mean of sample 1 is 72.90258788906006
Mean of sample 2 is 71.32012684727883
Mean of sample 3 is 70.93269338456311
Mean of sample 4 is 70.60049500802415
Mean of sample 5 is 69.36492983502723

We can see that the means differ slightly this shows sample variability.

Sampling distribution of mean

In [7]:
sample_mean=[]
for i in range(200):
    s=df.sample(n=30)
    sample_mean.append(s["marks"].mean())
means=pd.Series(sample_mean)
print("Sample Mean distribution")
means.describe()

Sample Mean distribution

count    200.000000
mean      70.259152
std        1.773335
min       65.316317
25%       69.145991
50%       70.381869
75%       71.371644
max       74.911531
dtype: float64

Sample of different sizes

In [14]:
sampleA = df.sample(n=30)
sampleB = df.sample(n=50)
sampleC = df.sample(n=200)
A_mean=sampleA["marks"].mean()
B_mean=sampleB["marks"].mean()
C_mean=sampleC["marks"].mean()
print (f"Mean of sample size 30 is {A_mean}")
print (f"Mean of sample size 50 is {B_mean}")
print (f"Mean of sample size 200 is {C_mean}")
print (print (f"Mean of population is {df["marks"].mean()}"))

Mean of sample size 30 is 71.53953298499742
Mean of sample size 50 is 67.31494336827626
Mean of sample size 200 is 69.68303460536617
Mean of population is 70.19332055822326
None

We can see that the mean of sample size 200 is nearly equal to the population mean. This shows that larger sample size gives better estimate.

Sampling with Replacement

In [21]:
replacement = df.sample(n = 50, replace = True)
without = df.sample(n = 50, replace = False)
print(replacement["marks"].mean())
print(without["marks"].mean())
print(replacement["marks"].std())
print(without["marks"].std())
df["marks"].std()

69.04828632831278
69.50302721395121
9.319303315295583
11.907517230760666

np.float64(9.792159381796756)

Random Variables

In [24]:
df["pass"] = df["marks"]>40
df

     student_id      marks  study_hours  pass
0             1  74.967142     7.798711  True
1             2  68.617357     6.849267  True
2             3  76.476885     5.119261  True
3             4  85.230299     3.706126  True
4             5  67.658466     6.396447  True
..          ...        ...          ...   ...
995         996  67.188997     7.140300  True
996         997  87.976865     4.946957  True
997         998  76.408429     3.236251  True
998         999  64.288210     4.673866  True
999        1000  75.725828     3.510195  True

[1000 rows x 4 columns]

Probability of Passing

In [33]:
prob_pass = (df[df["marks"]>50]["marks"].count())/df["marks"].count()
print(prob_pass)
# using mean
prob_pass=(df["marks"]>50).mean()
print(prob_pass)

0.983
0.983

Find probability of marks > 80

In [30]:
prob_greater80 = (df["marks"]>80).mean()
print(prob_greater80)

0.155

Conditional Probability

P(pass/ study_hours > 6)

In [36]:
study_hours_filtered = df[df["study_hours"] > 6]
P = (study_hours_filtered["marks"] > 50).mean()
print(P)

0.9759036144578314